# Generated by Django 4.1.3 on 2023-01-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_weathersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='auto_play_video',
            field=models.BooleanField(default=True),
        ),
    ]
