# Generated by Django 4.1.3 on 2023-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_homesettings_auto_play_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='mute_video',
            field=models.BooleanField(default=False),
        ),
    ]
