# Generated by Django 4.2 on 2023-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_homesettings_mute_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='video_volume',
            field=models.FloatField(default=1),
        ),
    ]
