# Generated by Django 4.0.6 on 2022-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_bookmarkcategory_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='welcome_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
