# Generated by Django 4.0.6 on 2022-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_theme_welcome_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='icon_name',
            field=models.CharField(default='GitHub', max_length=255),
            preserve_default=False,
        ),
    ]
