# Generated by Django 4.0.6 on 2022-07-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_bookmark_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(default='meaqua', max_length=255),
            preserve_default=False,
        ),
    ]
