# Generated by Django 4.0.6 on 2022-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_theme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mask_opacity',
            field=models.FloatField(default=0.5, max_length=1),
        ),
    ]
