# Generated by Django 4.0.6 on 2022-08-16 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_theme_mask_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
